.TH "Comment" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comment \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A class for the creation and modification of \fBPost\fP comments
.PP
\fBAuthor:\fP
.RS 4
Jonah Werre <jonahwerre@gmail.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1.0  Jonah Werre <jonahwerre@gmail.com>, 28 June, 2011 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
