.TH "Content" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Content \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabaseObject\fP.
.PP
Inherited by \fBPost\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexcerpt\fP ($length=EXCERPT_LENGTH, $link_text='more...', $allow= '< a >< em >< i >< strong >< b >< span >< br >< sup >< sub >< small >< strike >< abbr >< cite >< code >')"
.br
.ti -1c
.RI "\fBauthor\fP ()"
.br
.ti -1c
.RI "\fBset_tags\fP ($tags)"
.br
.ti -1c
.RI "\fBdelete_tag\fP ($tag_id)"
.br
.ti -1c
.RI "\fBtags\fP ($as_string=false, $delimiter=', ')"
.br
.ti -1c
.RI "\fBsnippets_complex\fP ()"
.br
.ti -1c
.RI "\fBsnippets\fP ()"
.br
.ti -1c
.RI "\fBget_link\fP ($include_tag=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcount_all\fP ()"
.br
.ti -1c
.RI "static \fBfind_all_by_type\fP ($order='weight ASC', $status=ContentStatus::PUBLISHED, $exclude=NULL, $include=NULL)"
.br
.ti -1c
.RI "static \fBfind_published_by_type_and_id\fP ($id)"
.br
.ti -1c
.RI "static \fBfind_last_created\fP ($limit=1)"
.br
.ti -1c
.RI "static \fBfind_by_title\fP ($title)"
.br
.ti -1c
.RI "static \fBfind_by_tag\fP ($tag)"
.br
.ti -1c
.RI "static \fBsearch\fP ($term)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBEXCERPT\fP = '<!--excerpt-->'"
.br
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$author_id\fP"
.br
.ti -1c
.RI "\fB$type\fP"
.br
.ti -1c
.RI "\fB$status\fP"
.br
.ti -1c
.RI "\fB$updated\fP"
.br
.ti -1c
.RI "\fB$created\fP"
.br
.ti -1c
.RI "\fB$weight\fP"
.br
.ti -1c
.RI "\fB$slug\fP"
.br
.ti -1c
.RI "\fB$title\fP"
.br
.ti -1c
.RI "\fB$body\fP"
.br
.ti -1c
.RI "\fB$parent_id\fP"
.br
.ti -1c
.RI "\fB$category_id\fP"
.br
.ti -1c
.RI "\fB$template\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$table_name\fP = 'content'"
.br
.ti -1c
.RI "static \fB$db_fields\fP = array( 'id', 'author_id', 'type', 'status', 'updated', 'created', 'weight', 'slug', 'title', 'body', 'parent_id', 'category_id', 'template')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Content::author ()"Returns author of the content as a \fBUser\fP object
.PP
\fBReturns:\fP
.RS 4
\fBUser\fP 
.RE
.PP

.SS "static Content::count_all ()\fC [static]\fP"Count number of items in $table_name 
.PP
\fBReturns:\fP
.RS 4
int | boolean 
.RE
.PP

.SS "Content::delete_tag ($tag_id)"Deletes a tag based on its id
.PP
\fBParameters:\fP
.RS 4
\fI$tag_id\fP - The id of the tag to be deleted 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "Content::excerpt ($length = \fCEXCERPT_LENGTH\fP, $link_text = \fC'more...'\fP, $allow = \fC'<a><em><i><strong><b><span><br><sup><sub><small><strike><abbr><cite><code>'\fP)"Returns an excerpt from post. To specify an excerpt lenght user the in the content body or specify an EXCERPT_LENGTH in config.php
.PP
\fBParameters:\fP
.RS 4
\fI$length\fP = EXCERPT_LENGTH - The lenght of the excerpt to be returned rounded to the last space. This will be ingored if the excerpt flag () is specified in the body. 
.br
\fI$link_text\fP = more... - The text to use use for the 'more' link at the end of the excpert. A link will not be used if NULL is given. 
.br
\fI$allow\fP = '\fI\fI\fB\fB
.br
\*{\*<<strike><abbr><cite>\fC' - a list of html tags to allow in excerpt. inline elements allowed by default \fP\*> \*} \fP\fP\fP\fP
.RE
.PP
\fBReturns:\fP
.RS 4
\fI\fI\fB\fB\*{\*<\fC string \fP\*> \*} \fP\fP\fP\fP
.RE
.PP

.SS "static Content::find_all_by_type ($order = \fC'weight ASC'\fP, $status = \fCContentStatus::PUBLISHED\fP, $exclude = \fCNULL\fP, $include = \fCNULL\fP)\fC [static]\fP"Returns all \fBContent\fP 
.PP
\fBParameters:\fP
.RS 4
\fI$order,='weight\fP ASC" - The field which the output is orders by 
.br
\fI$status,=ContentType::PUBLISHED\fP - The status of the contents (ContentStatus::PUBLISHED | ContentStatus::DRAFT | NULL ) 
.br
\fI$exclude\fP = NULL - An array of content ids to exclude 
.br
\fI$include\fP = NULL - An array of content ids to include (excuding all others) 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Content::find_by_tag ($tag)\fC [static]\fP"Finds all \fBContent\fP link to provided tags 
.PP
\fBParameters:\fP
.RS 4
\fIinteger\fP | string $tag - An id or tag name; 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Content::find_by_title ($title)\fC [static]\fP"Finds \fBContent\fP by its title 
.PP
\fBParameters:\fP
.RS 4
\fI$title\fP - The title or slug of the \fBContent\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBContent\fP 
.RE
.PP

.SS "static Content::find_last_created ($limit = \fC1\fP)\fC [static]\fP"Returns last created published \fBContent\fP 
.PP
\fBParameters:\fP
.RS 4
\fI$limit,=1\fP - The max amount of \fBContent\fP objects to return 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Content::find_published_by_type_and_id ($id)\fC [static]\fP"Returns all published \fBContent\fP by \fBContent\fP id 
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Content::get_link ($include_tag = \fCfalse\fP)"Returns a link for the content
.PP
\fBParameters:\fP
.RS 4
\fI$include_tag\fP = false - if true the link is wapped in an anchor tag 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "static Content::search ($term)\fC [static]\fP"Searches content for related term 
.PP
\fBParameters:\fP
.RS 4
\fI$term\fP - search term 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Content::set_tags ($tags)"sets new tags to content
.PP
\fBParameters:\fP
.RS 4
\fI$tags\fP - an array of strings 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Content::snippets ()"Returns an associative array of Snippets for this \fBContent\fP
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Content::snippets_complex ()"Returns an array of \fBSnippet\fP objects for this \fBContent\fP
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Content::tags ($as_string = \fCfalse\fP, $delimiter = \fC', '\fP)"Returns all tags attached to \fBContent\fP
.PP
\fBParameters:\fP
.RS 4
\fI$as_string\fP = false - return tag names as string. 
.br
\fI$delimiter\fP = ', ' - delimiter for string output. 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
