.TH "ContentStatus" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentStatus \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBget_types\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBPUBLISHED\fP = 'published'"
.br
.ti -1c
.RI "const \fBDRAFT\fP = 'draft'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
