.TH "Image" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMedia\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBattach_file\fP ($file)"
.br
.ti -1c
.RI "\fBresize\fP ($new_width, $new_height, $option=self::EXACT, $offset=array('x'=>0,'y'=>0))"
.br
.ti -1c
.RI "\fBsave_image\fP ($imageQuality='100', $save_as=NULL)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBis_image\fP ($filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBIMG_GIF\fP = 'image/gif'"
.br
.ti -1c
.RI "const \fBIMG_JPEG\fP = 'image/jpeg'"
.br
.ti -1c
.RI "const \fBIMG_PNG\fP = 'image/png'"
.br
.ti -1c
.RI "const \fBEXACT\fP = 'exact'"
.br
.ti -1c
.RI "const \fBAUTO\fP = 'auto'"
.br
.ti -1c
.RI "const \fBLANDSCAPE\fP = 'landscape'"
.br
.ti -1c
.RI "const \fBPORTRAIT\fP = 'portrait'"
.br
.ti -1c
.RI "const \fBCROP\fP = 'crop'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Image::attach_file ($file)"Sets \fBImage\fP attributes. Useage: attach_file( $_FILE['uploaded_file'] );
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP - An associative array of items uploaded to the current script via the HTTP POST method 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Reimplemented from \fBMedia\fP.
.SS "static Image::is_image ($filename)\fC [static]\fP"checks to see if file is a jpg, jpeg, gif, or png
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP - the file to check 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "Image::resize ($new_width, $new_height, $option = \fCself::EXACT\fP, $offset = \fCarray('x'=>0,'y'=>0)\fP)"Resize and image
.PP
\fBParameters:\fP
.RS 4
\fI$new_width\fP - The new width of the image 
.br
\fI$new_height\fP - The new height of the image 
.br
\fI$option,=self::EXACT\fP - The options to use ( Image::EXACT | Image::PORTRAIT | Images::LANDSCAPE | Images::Crop | Images::AUTO ) 
.br
\fI$offset\fP = array('x'=>0, 'y'=>0) - An offset for the crop option 
.RE
.PP
\fBReturns:\fP
.RS 4
null 
.RE
.PP

.SS "Image::save_image ($imageQuality = \fC'100'\fP, $save_as = \fCNULL\fP)"Saves a new resized image
.PP
\fBParameters:\fP
.RS 4
\fI$imageQuality,='100'\fP - The quality of the image 
.br
\fI$save_as,=NULL\fP - Use to save as a copy without overwriting the current \fBImage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
