.TH "Mail" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mail \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBemail\fP ($subject, $message, $from_name=NULL, $from_email=NULL, $to_name=NULL, $to_email=NULL)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Mail::email ($subject, $message, $from_name = \fCNULL\fP, $from_email = \fCNULL\fP, $to_name = \fCNULL\fP, $to_email = \fCNULL\fP)"Sends an email
.PP
\fBParameters:\fP
.RS 4
\fI$subject\fP - email subject; 
.br
\fI$message\fP - email message; 
.br
\fI$from_name\fP - from names; 
.br
\fI$from_email-\fP from email; 
.br
\fIstring\fP | array $to_name - an array or string recipeint name(s); 
.br
\fIstring\fP | array $to_email - an array or string recipeint email address(es); 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
