.TH "Navigation" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Navigation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoutput_nav\fP ()"
.br
.ti -1c
.RI "\fBoutput_sitemap\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBoutput_categories\fP ($exclude=NULL)"
.br
.ti -1c
.RI "static \fBsubnav\fP ($parent)"
.br
.ti -1c
.RI "static \fBget_link\fP ($content, $include_tag=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$nav_tag\fP = 'ul'"
.br
.ti -1c
.RI "\fB$child_tag\fP = 'li'"
.br
.ti -1c
.RI "\fB$root_class\fP = 'nav'"
.br
.ti -1c
.RI "\fB$subnav_class\fP = 'subnav'"
.br
.ti -1c
.RI "\fB$subnav2_class\fP = 'subnav2'"
.br
.ti -1c
.RI "\fB$current_page\fP"
.br
.ti -1c
.RI "\fB$exclude\fP = NULL"
.br
.ti -1c
.RI "\fB$include\fP = NULL"
.br
.ti -1c
.RI "\fB$additional\fP = NULL"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Navigation::get_link ($content, $include_tag = \fCfalse\fP)\fC [static]\fP"Returns the url for a \fBPage\fP or \fBPost\fP
.PP
\fBParameters:\fP
.RS 4
\fIinteger\fP | string $content - the id, title, slug, or \fBContent\fP object for which you want the link 
.br
\fI$include_tag\fP - if true, returns the link in an anchor tag 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "static Navigation::output_categories ($exclude = \fCNULL\fP)\fC [static]\fP"Outputs a list of categories 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "Navigation::output_nav ()"Outputs a complex navigational menu with sub-naviation 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "Navigation::output_sitemap ()"Outputs a simple site map 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "string Navigation::subnav ($parent)\fC [static]\fP"outputs sub-pages in a list
.PP
\fBParameters:\fP
.RS 4
\fI$parent\fP \fBPage\fP - The parent page of the subpages to output 
.RE
.PP
\fBReturns:\fP
.RS 4
void
.RE
.PP
the class used for the subnav 
.SH "Member Data Documentation"
.PP 
.SS "Navigation::$current_page"$current_page - typically the global page object 

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
