.TH "Pagination" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pagination \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($current_page=1, $per_page=ITEMS_PER_PAGE, $total_items=0)"
.br
.ti -1c
.RI "\fBoffset\fP ()"
.br
.ti -1c
.RI "\fBprevious_page\fP ()"
.br
.ti -1c
.RI "\fBnext_page\fP ()"
.br
.ti -1c
.RI "\fBhas_previous_page\fP ()"
.br
.ti -1c
.RI "\fBhas_next_page\fP ()"
.br
.ti -1c
.RI "\fBnecessary\fP ()"
.br
.ti -1c
.RI "\fBoutput_controls\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$current_page\fP"
.br
.ti -1c
.RI "\fB$per_page\fP"
.br
.ti -1c
.RI "\fB$total_items\fP"
.br
.ti -1c
.RI "\fB$total_pages\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
