.TH "Poll" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poll \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabaseObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($question, $options)"
.br
.ti -1c
.RI "\fBinitialize\fP ()"
.br
.ti -1c
.RI "\fBoutput_options\fP ($class='poll_option')"
.br
.ti -1c
.RI "\fBoutput_results\fP ()"
.br
.ti -1c
.RI "\fBget_results\fP ()"
.br
.ti -1c
.RI "\fBvote\fP ($answer)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$question\fP = ''"
.br
.ti -1c
.RI "\fB$options\fP = array()"
.br
.ti -1c
.RI "\fB$voted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for polling 

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
