.TH "Post" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Post \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContent\fP.
.PP
Inherited by \fBPage\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBis_in_category\fP ($category)"
.br
.ti -1c
.RI "\fBcategory_name\fP ()"
.br
.ti -1c
.RI "\fBget_next_post\fP ($category=NULL)"
.br
.ti -1c
.RI "\fBget_previous_post\fP ($category=NULL)"
.br
.ti -1c
.RI "\fBget_adjacent_post\fP ($category=NULL, $previous=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfind_by_category_id\fP ($id, $order='created DESC', $limit=NULL, $offset=NULL, $return_count=false)"
.br
.ti -1c
.RI "static \fBfind_by_category_title\fP ($titles, $order='created DESC', $limit=NULL, $offset=NULL, $return_count=false)"
.br
.ti -1c
.RI "static \fBfind_except_in_categories\fP ($categories, $order='created DESC', $limit=NULL, $offset=NULL, $return_count=false)"
.br
.ti -1c
.RI "static \fBfind_by_tag\fP ($tag, $order='created DESC', $limit=NULL, $offset=NULL, $return_count=false)"
.br
.ti -1c
.RI "static \fBfind_by_dates\fP ($month, $day=NULL, $year=NULL, $categories=NULL, $order='created DESC', $limit=NULL, $offset=NULL, $return_count=false)"
.br
.ti -1c
.RI "static \fBget_dates\fP ($month=NULL, $year=NULL, $categories=NULL)"
.br
.ti -1c
.RI "static \fBget_authors\fP ($categories)"
.br
.ti -1c
.RI "static \fBget_categories\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Post::category_name ()"Retuns the current category name 
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "static Post::find_by_category_id ($id, $order = \fC'created DESC'\fP, $limit = \fCNULL\fP, $offset = \fCNULL\fP, $return_count = \fCfalse\fP)\fC [static]\fP"Returns an array of content by
.PP
\fBParameters:\fP
.RS 4
\fIint\fP id - category id 
.br
\fI$order\fP = 'created DESC' - The field name by which to oder the results. Use DESC or ASC to swap order 
.br
\fI$limit\fP int - limit the amount of content to retrieve 
.br
\fI$offset\fP int - offset of the first row to return 
.br
\fI$return_count\fP boolen - If true will return a row count instead of an array of \fBPost\fP object. Usefull for doing pagination. 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Post::find_by_category_title ($titles, $order = \fC'created DESC'\fP, $limit = \fCNULL\fP, $offset = \fCNULL\fP, $return_count = \fCfalse\fP)\fC [static]\fP"Returns an array of Posts by category name
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP | array $titles - The \fBCategory\fP title as a string or an array of strings 
.br
\fI$order\fP = 'created DESC' - The field name by which to oder the results. Use DESC or ASC to swap order 
.br
\fI$limit\fP int - limit the amount of content to retrieve 
.br
\fI$offset\fP int - offset of the first row to return 
.br
\fI$return_count\fP boolen - If true will return a row count instead of an array of \fBPost\fP object. Usefull for doing pagination. 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Post::find_by_dates ($month, $day = \fCNULL\fP, $year = \fCNULL\fP, $categories = \fCNULL\fP, $order = \fC'created DESC'\fP, $limit = \fCNULL\fP, $offset = \fCNULL\fP, $return_count = \fCfalse\fP)\fC [static]\fP"Retrives all the post created on a specific month day year.
.PP
\fBParameters:\fP
.RS 4
\fI$month\fP - The Post's month it was created in 
.br
\fI$day,=NULL\fP - The Post's day it was created in 
.br
\fI$year,=NULL\fP - The Post's year it was created in 
.br
\fIarray\fP | string $categories=NULL - Only retive posts of specific categories 
.br
\fI$order\fP = 'created DESC' - The field name by which to order the results. Use DESC or ASC to swap order 
.br
\fI$limit\fP - limit the amount of content to retrieve 
.br
\fI$offset\fP - offset of the first row to return 
.br
\fI$return_count\fP boolen - If true will return a row count instead of an array of \fBPost\fP object. Usefull for doing pagination. 
.RE
.PP
\fBReturns:\fP
.RS 4
array - Array containg result Posts 
.RE
.PP

.SS "static Post::find_by_tag ($tag, $order = \fC'created DESC'\fP, $limit = \fCNULL\fP, $offset = \fCNULL\fP, $return_count = \fCfalse\fP)\fC [static]\fP"Returns an array content linked to specified tag
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP | integer $tag - A \fBTag\fP id or tag name 
.br
\fI$order\fP = 'created DESC' - The field name by which to order the results. Use DESC or ASC to swap order 
.br
\fI$limit\fP - limit the amount of content to retrieve 
.br
\fI$offset\fP - offset of the first row to return 
.br
\fI$return_count\fP boolen - If true will return a row count instead of an array of \fBPost\fP object. Usefull for doing pagination. 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Post::find_except_in_categories ($categories, $order = \fC'created DESC'\fP, $limit = \fCNULL\fP, $offset = \fCNULL\fP, $return_count = \fCfalse\fP)\fC [static]\fP"Returns an array content excluding provided categories ids
.PP
\fBParameters:\fP
.RS 4
\fIcategories\fP array - categories to exclude 
.br
\fI$order\fP = 'created DESC' - The field name by which to order the results. Use DESC or ASC to swap order 
.br
\fI$limit\fP - limit the amount of content to retrieve 
.br
\fI$offset\fP - offset of the first row to return 
.br
\fI$return_count\fP boolen - If true will return a row count instead of an array of \fBPost\fP object. Usefull for doing pagination. 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Post::get_adjacent_post ($category = \fCNULL\fP, $previous = \fCfalse\fP)"Returns the an adjacently created post
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP | number $category = NULL - restrict posts to specified category 
.br
\fI$previous\fP = true - true will return the next post false will return the previous 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPost\fP 
.RE
.PP

.SS "static Post::get_authors ($categories)\fC [static]\fP"Returns all the usres who have publish Posts
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP | string - Specify a specific category of Posts; 
.RE
.PP
\fBReturns:\fP
.RS 4
array - Returns and array of \fBUser\fP objects 
.RE
.PP

.SS "static Post::get_categories ()\fC [static]\fP"Returns all categories
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "static Post::get_dates ($month = \fCNULL\fP, $year = \fCNULL\fP, $categories = \fCNULL\fP)\fC [static]\fP"Retrives all the months and or years Posts have been created. This is useful when created navigation based on dates;
.PP
\fBParameters:\fP
.RS 4
\fI$month\fP - The month to search 
.br
\fI$year,=NULL\fP - The year to search 
.br
\fIarray\fP | string $categories=NULL - Only search Posts of specific categories 
.RE
.PP
\fBReturns:\fP
.RS 4
array - An array of months all posts were created 
.RE
.PP

.SS "Post::get_next_post ($category = \fCNULL\fP)"Returns the next created post
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP | number $category = NULL - restrict posts to specified category 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPost\fP 
.RE
.PP

.SS "Post::get_previous_post ($category = \fCNULL\fP)"Returns the previoulsly created post
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP | number $category = NULL - restrict posts to specified category 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPost\fP 
.RE
.PP

.SS "Post::is_in_category ($category)"Checks to see if the post is in a \fBCategory\fP
.PP
\fBParameters:\fP
.RS 4
\fIint\fP | string $category - The category 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
