.TH "Snippet" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Snippet \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabaseObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($content_id=NULL, $name=NULL, $value=NULL)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfind_by_content_id\fP ($content_id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$content_id\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$value\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$table_name\fP = 'snippets'"
.br
.ti -1c
.RI "static \fB$db_fields\fP = array('id', 'content_id', 'name', 'value' )"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Snippet::find_by_content_id ($content_id)\fC [static]\fP"finds a \fBSnippet\fP object via it's content id 

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
