.TH "Tag" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabaseObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsave\fP ($content_id)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfind_by_content_id\fP ($content_id=0)"
.br
.ti -1c
.RI "static \fBfind_all_in_category\fP ($category)"
.br
.ti -1c
.RI "static \fBclear_tags_for_content\fP ($content_id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$tag\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$table_name\fP = 'tags'"
.br
.ti -1c
.RI "static \fB$db_fields\fP = array('id', 'tag')"
.br
.ti -1c
.RI "static \fB$x_table_name\fP = 'content_x_tags'"
.br
.ti -1c
.RI "static \fB$db_x_fields\fP = array('content_id', 'tag_id')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Tag::clear_tags_for_content ($content_id)\fC [static]\fP"Clears all tags for content
.PP
\fBParameters:\fP
.RS 4
\fI$content_id\fP - id of content to clear tags 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "static Tag::find_all_in_category ($category)\fC [static]\fP"Returns all the tags for Posts in a specific \fBCategory\fP
.PP
\fBParameters:\fP
.RS 4
\fIinteger\fP | string | array $category - The category as an id, title or array of titles 
.RE
.PP
\fBReturns:\fP
.RS 4
array - 
.RE
.PP

.SS "static Tag::find_by_content_id ($content_id = \fC0\fP)\fC [static]\fP"Returns an array of tags linked to a \fBContent\fP
.PP
\fBParameters:\fP
.RS 4
\fI$content_id\fP - The id of the \fBContent\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "Tag::save ($content_id)"Check to see if record exists and creates it if not or updates if it does.
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
