.TH "Template" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Template \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparse_template\fP ($extra=NULL)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinclude_template\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$entries\fP = array()"
.br
.ti -1c
.RI "\fB$template\fP"
.br
.ti -1c
.RI "\fB$template_content\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for processing theme templates 
.SH "Member Function Documentation"
.PP 
.SS "static Template::include_template ()\fC [static]\fP"description
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP - param description 
.RE
.PP
\fBReturns:\fP
.RS 4
string - return description 
.RE
.PP

.SS "Template::parse_template ($extra = \fCNULL\fP)"Parses the template
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP - Additional content 
.RE
.PP
\fBReturns:\fP
.RS 4
string - The markup 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Template::$entries = array()"Stores the entries to be parsed into the template 
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
