.TH "URLRewrite" 3 "Fri Oct 7 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
URLRewrite \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($page)"
.br
.ti -1c
.RI "\fBadd_rule\fP ()"
.br
.ti -1c
.RI "\fBremove_rule\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBAPACHE\fP = 'apache'"
.br
.ti -1c
.RI "const \fBIIS\fP = 'iis'"
.br
.ti -1c
.RI "\fB$page\fP"
.br
.ti -1c
.RI "\fB$key_prefix\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for writing and modifyling rewrite map. It's very crude but it's a start
.PP
TODO:: this class needs to set up the initial rewrite settings in .htdocs and web.config 
.SH "Member Function Documentation"
.PP 
.SS "URLRewrite::add_rule ()"Adds a rule to rewrite map 
.SS "URLRewrite::remove_rule ()"Remove rule from rewrite map 

.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
