.TH "User" 3 "Fri Aug 5 2011" "Version 1.0" "Launchpad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabaseObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfull_name\fP ()"
.br
.ti -1c
.RI "\fBprofile_image\fP ($alternate=NULL)"
.br
.ti -1c
.RI "\fBrole_title\fP ()"
.br
.ti -1c
.RI "\fBgenerate_random_password\fP ($length=10)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBauthenticate\fP ($username='', $password='')"
.br
.ti -1c
.RI "static \fBget_user\fP ($user_info)"
.br
.ti -1c
.RI "static \fBexists\fP ($user_info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$username\fP"
.br
.ti -1c
.RI "\fB$first_name\fP"
.br
.ti -1c
.RI "\fB$last_name\fP"
.br
.ti -1c
.RI "\fB$email\fP"
.br
.ti -1c
.RI "\fB$password\fP"
.br
.ti -1c
.RI "\fB$role\fP"
.br
.ti -1c
.RI "\fB$bio\fP"
.br
.ti -1c
.RI "\fB$image_id\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$table_name\fP = 'users'"
.br
.ti -1c
.RI "static \fB$db_fields\fP = array( 'id', 'first_name', 'last_name', 'username', 'email', 'password', 'bio', 'role', 'image_id' )"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static User::authenticate ($username = \fC''\fP, $password = \fC''\fP)\fC [static]\fP"Athentictates username and password combination.
.PP
\fBParameters:\fP
.RS 4
\fI$username,;\fP 
.br
\fI$password,;\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBUser\fP | boolean 
.RE
.PP

.SS "static User::exists ($user_info)\fC [static]\fP"Checks to see if a username or email already exist
.PP
\fBParameters:\fP
.RS 4
\fI$user_info\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "User::full_name ()"Return the full name of the current user
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "User::generate_random_password ($length = \fC10\fP)"Generate a random password
.PP
\fBParameters:\fP
.RS 4
\fI$length\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "static User::get_user ($user_info)\fC [static]\fP"Retrieves user via username or email
.PP
\fBParameters:\fP
.RS 4
\fI$user_info\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBUser\fP | boolean 
.RE
.PP

.SS "User::profile_image ($alternate = \fCNULL\fP)"returns a profile image that corresponds to the user
.PP
\fBReturns:\fP
.RS 4
\fBImage\fP 
.RE
.PP

.SS "User::role_title ()"Returns the integer role as it's title equivalent
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Launchpad from the source code.
